name: Generate the plots

on:
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install nix
        uses: cachix/install-nix-action@v18
      - name: Extract the changes
        run: nix run .#extract
      - name: Print how many commits have been extracted
        run: nix develop -c sqlite3 ./res.db 'select count(*) from commits'
      - name: Render the graphs
        run: nix run .#analyse
      - name: Commit the graphs if changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest plots: ${timestamp}" || exit 0
          git push
      - name: Render the HTML
        run: nix run .#render
      - name: Create pages directory
        run: |-
          mkdir -p pages
          cp index.html pages
          cp -r plots pages/
      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: pages
